application: compressor-head
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /license
  static_files: license.txt
  upload: license.txt
  secure: optional

- url: /image
  static_files: got-map.jpg
  upload: got-map.jpg
  secure: optional

- url: .*
  script: main.app
  secure: optional

libraries:
- name: webapp2
  version: "2.5.2"
